In [6]:
from citipy import citipy
import numpy as np
import pandas as pd

In [7]:
# Create a set of random latitude and longitude combinations

lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [8]:
# Add the Latitude and Longitudes to a list

coordinates = list(lat_lngs)

In [9]:
# Create a list for holding the cities

cities = []

# Identify nearest city for each latitude and longitude combination

for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If the city is unique, add it to the cities list
    
    if city not in cities:
        cities.append(city)
        
len(cities)

593

In [10]:
# Import the request library

import requests

from datetime import datetime
from config import weather_api_key

In [11]:
# Starting URL for Weather Map API Call

url = f"http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID={weather_api_key}"

In [12]:
# List of city data

city_data = []

# Print to logger

print('Beginning Data Retrieval')
print('-' * 25)

# Create a counter

record_count = 1
set_count = 1
for index, city in enumerate(cities):
    
    # City groups in sets of 50 for logging purposes
    
    if(index % 50 == 0 and index >= 50):
        set_count += 1
        record_count = 1
        
    # URL with each city
    
    city_url = f"{url}&q={city.replace(' ', '+')}"
    
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    record_count += 1
    
    try:
        city_weather = requests.get(city_url).json()
        
        # Split max temp, humidity, and cloudiness
        
        city_lat = city_weather['coord']['lat']
        city_lng = city_weather['coord']['lon']
        city_max_temp = city_weather['main']['temp_max']
        city_humidity = city_weather['main']['humidity']
        city_clouds = city_weather['clouds']['all']
        city_wind = city_weather['wind']['speed']
        city_country = city_weather['sys']['country']
        city_weather_description = city_weather['weather'][0]['description']
        try:
            city_rain_inches = city_weather['rain']['1h']
        except KeyError:
            city_rain_inches = 0
        try:
            city_snow_inches = city_weather['snow']['1h']
        except KeyError:
            city_snow_inches = 0
            
        # City information into city_data
        
        city_data.append(
        {
            'City': city,
            'Lat': city_lat,
            'Lng': city_lng,
            'Max Temp': city_max_temp,
            'Current Description': city_weather_description,
            'Rain (inches)': city_rain_inches,
            'Snow (inches)': city_snow_inches,
            'Humidity': city_humidity,
            'Cloudiness': city_clouds,
            'Wind Speed': city_wind,
            'Country': city_country
        })
    except:
        print('City not found. Skipping...')
        pass
    
# Data Loading is complete

print('-' * 20)
print('Data Retrieval Complete')
print('-' * 20)

Beginning Data Retrieval
-------------------------
Processing Record 1 of Set 1 | souillac
Processing Record 2 of Set 1 | albany
Processing Record 3 of Set 1 | high rock
Processing Record 4 of Set 1 | avarua
Processing Record 5 of Set 1 | tha chang
Processing Record 6 of Set 1 | jamestown
Processing Record 7 of Set 1 | morden
Processing Record 8 of Set 1 | bethel
Processing Record 9 of Set 1 | talnakh
Processing Record 10 of Set 1 | severo-kurilsk
Processing Record 11 of Set 1 | freeport
Processing Record 12 of Set 1 | kutum
Processing Record 13 of Set 1 | pevek
Processing Record 14 of Set 1 | safwah
City not found. Skipping...
Processing Record 15 of Set 1 | kahului
Processing Record 16 of Set 1 | arraial do cabo
Processing Record 17 of Set 1 | cockburn town
Processing Record 18 of Set 1 | rikitea
Processing Record 19 of Set 1 | manadhoo
Processing Record 20 of Set 1 | coihaique
Processing Record 21 of Set 1 | praia
Processing Record 22 of Set 1 | punta arenas
Processing Record 23 of Set 1 | honiara
Processing Record 24 of Set 1 | trairi
Processing Record 25 of Set 1 | kamskiye polyany
Processing Record 26 of Set 1 | butaritari
Processing Record 27 of Set 1 | yulara
Processing Record 28 of Set 1 | qaanaaq
Processing Record 29 of Set 1 | vardo
Processing Record 30 of Set 1 | ushuaia
Processing Record 31 of Set 1 | belushya guba
City not found. Skipping...
Processing Record 32 of Set 1 | victoria
Processing Record 33 of Set 1 | sitka
Processing Record 34 of Set 1 | songjianghe
Processing Record 35 of Set 1 | lebu
Processing Record 36 of Set 1 | tabialan
City not found. Skipping...
Processing Record 37 of Set 1 | vizinga
Processing Record 38 of Set 1 | hasaki
Processing Record 39 of Set 1 | kamenskoye
City not found. Skipping...
Processing Record 40 of Set 1 | bubaque
Processing Record 41 of Set 1 | tuktoyaktuk
Processing Record 42 of Set 1 | puerto ayora
Processing Record 43 of Set 1 | san patricio
Processing Record 44 of Set 1 | faanui
Processing Record 45 of Set 1 | weyburn
Processing Record 46 of Set 1 | naduvattam
Processing Record 47 of Set 1 | kapaa
Processing Record 48 of Set 1 | acapulco
Processing Record 49 of Set 1 | hobart
Processing Record 50 of Set 1 | bluff
Processing Record 1 of Set 2 | govindgarh
Processing Record 2 of Set 2 | winnemucca
Processing Record 3 of Set 2 | sechura
Processing Record 4 of Set 2 | aberdeen
Processing Record 5 of Set 2 | petushki
Processing Record 6 of Set 2 | orlik
Processing Record 7 of Set 2 | saint-philippe
Processing Record 8 of Set 2 | port alfred
Processing Record 9 of Set 2 | poddorye
Processing Record 10 of Set 2 | boddam
Processing Record 11 of Set 2 | norman wells
Processing Record 12 of Set 2 | itarema
Processing Record 13 of Set 2 | saint george
Processing Record 14 of Set 2 | yumen
Processing Record 15 of Set 2 | sanghar
Processing Record 16 of Set 2 | havre-saint-pierre
Processing Record 17 of Set 2 | canutama
Processing Record 18 of Set 2 | east london
Processing Record 19 of Set 2 | mullaitivu
City not found. Skipping...
Processing Record 20 of Set 2 | manoel urbano
Processing Record 21 of Set 2 | luderitz
Processing Record 22 of Set 2 | mataura
Processing Record 23 of Set 2 | lavrentiya
Processing Record 24 of Set 2 | bredasdorp
Processing Record 25 of Set 2 | golden
Processing Record 26 of Set 2 | khatanga
Processing Record 27 of Set 2 | ribeira grande
Processing Record 28 of Set 2 | otaru
Processing Record 29 of Set 2 | pangai
Processing Record 30 of Set 2 | torbay
Processing Record 31 of Set 2 | alta floresta
Processing Record 32 of Set 2 | saldanha
Processing Record 33 of Set 2 | poum
Processing Record 34 of Set 2 | gamba
Processing Record 35 of Set 2 | burnie
Processing Record 36 of Set 2 | geraldton
Processing Record 37 of Set 2 | cape town
Processing Record 38 of Set 2 | namatanai
Processing Record 39 of Set 2 | tual
Processing Record 40 of Set 2 | new norfolk
Processing Record 41 of Set 2 | edson
Processing Record 42 of Set 2 | longyearbyen
Processing Record 43 of Set 2 | ponta do sol
Processing Record 44 of Set 2 | illoqqortoormiut
City not found. Skipping...
Processing Record 45 of Set 2 | porto novo
Processing Record 46 of Set 2 | iqaluit
Processing Record 47 of Set 2 | busselton
Processing Record 48 of Set 2 | hermanus
Processing Record 49 of Set 2 | bereda
Processing Record 50 of Set 2 | cidreira
Processing Record 1 of Set 3 | tessalit
Processing Record 2 of Set 3 | sambhar
Processing Record 3 of Set 3 | saleaula
City not found. Skipping...
Processing Record 4 of Set 3 | grand river south east
City not found. Skipping...
Processing Record 5 of Set 3 | salina
Processing Record 6 of Set 3 | thompson
Processing Record 7 of Set 3 | esperance
Processing Record 8 of Set 3 | launceston
Processing Record 9 of Set 3 | montrose
Processing Record 10 of Set 3 | tasiilaq
Processing Record 11 of Set 3 | barrow
Processing Record 12 of Set 3 | bumba
Processing Record 13 of Set 3 | kupang
Processing Record 14 of Set 3 | liberty
Processing Record 15 of Set 3 | mys shmidta
City not found. Skipping...
Processing Record 16 of Set 3 | bandarbeyla
Processing Record 17 of Set 3 | kyaikkami
Processing Record 18 of Set 3 | nikolskoye
Processing Record 19 of Set 3 | sao joao da barra
Processing Record 20 of Set 3 | carnarvon
Processing Record 21 of Set 3 | chateauroux
Processing Record 22 of Set 3 | gemena
Processing Record 23 of Set 3 | tornio
Processing Record 24 of Set 3 | nalut
Processing Record 25 of Set 3 | salalah
Processing Record 26 of Set 3 | gojra
Processing Record 27 of Set 3 | vao
Processing Record 28 of Set 3 | hithadhoo
Processing Record 29 of Set 3 | ruatoria
City not found. Skipping...
Processing Record 30 of Set 3 | wyndham
Processing Record 31 of Set 3 | kamaishi
Processing Record 32 of Set 3 | cabo san lucas
Processing Record 33 of Set 3 | aklavik
Processing Record 34 of Set 3 | hofn
Processing Record 35 of Set 3 | margate
Processing Record 36 of Set 3 | soyo
Processing Record 37 of Set 3 | hilo
Processing Record 38 of Set 3 | plettenberg bay
Processing Record 39 of Set 3 | bilibino
Processing Record 40 of Set 3 | yellowknife
Processing Record 41 of Set 3 | neiafu
Processing Record 42 of Set 3 | atuona
Processing Record 43 of Set 3 | taolanaro
City not found. Skipping...
Processing Record 44 of Set 3 | redding
Processing Record 45 of Set 3 | floro
Processing Record 46 of Set 3 | mersing
Processing Record 47 of Set 3 | bathsheba
Processing Record 48 of Set 3 | waterloo
Processing Record 49 of Set 3 | maceio
Processing Record 50 of Set 3 | alice springs
Processing Record 1 of Set 4 | santo antonio do ica
Processing Record 2 of Set 4 | mount isa
Processing Record 3 of Set 4 | podgornoye
Processing Record 4 of Set 4 | attawapiskat
City not found. Skipping...
Processing Record 5 of Set 4 | cururupu
Processing Record 6 of Set 4 | lafayette
Processing Record 7 of Set 4 | saint anthony
Processing Record 8 of Set 4 | tougue
Processing Record 9 of Set 4 | port macquarie
Processing Record 10 of Set 4 | buckingham
Processing Record 11 of Set 4 | castro
Processing Record 12 of Set 4 | batsfjord
Processing Record 13 of Set 4 | warqla
City not found. Skipping...
Processing Record 14 of Set 4 | khlung
Processing Record 15 of Set 4 | urengoy
Processing Record 16 of Set 4 | sarangani
Processing Record 17 of Set 4 | linxia
Processing Record 18 of Set 4 | lhokseumawe
Processing Record 19 of Set 4 | san jose
Processing Record 20 of Set 4 | khani
Processing Record 21 of Set 4 | quzhou
Processing Record 22 of Set 4 | vaini
Processing Record 23 of Set 4 | providencia
Processing Record 24 of Set 4 | guerrero negro
Processing Record 25 of Set 4 | sakakah
Processing Record 26 of Set 4 | jiuquan
Processing Record 27 of Set 4 | sabang
Processing Record 28 of Set 4 | jenjarom
Processing Record 29 of Set 4 | georgetown
Processing Record 30 of Set 4 | upernavik
Processing Record 31 of Set 4 | pokrovsk
Processing Record 32 of Set 4 | lunglei
Processing Record 33 of Set 4 | husavik
Processing Record 34 of Set 4 | cascais
Processing Record 35 of Set 4 | robat karim
Processing Record 36 of Set 4 | raga
Processing Record 37 of Set 4 | jalu
Processing Record 38 of Set 4 | port blair
Processing Record 39 of Set 4 | kaitangata
Processing Record 40 of Set 4 | saskylakh

Processing Record 41 of Set 4 | callaway
Processing Record 42 of Set 4 | chuy
Processing Record 43 of Set 4 | maltahohe
Processing Record 44 of Set 4 | jutai
Processing Record 45 of Set 4 | vaitupu
City not found. Skipping...
Processing Record 46 of Set 4 | sentyabrskiy
City not found. Skipping...
Processing Record 47 of Set 4 | gamboula
Processing Record 48 of Set 4 | belmonte
Processing Record 49 of Set 4 | yerbogachen
Processing Record 50 of Set 4 | bara
Processing Record 1 of Set 5 | nara
Processing Record 2 of Set 5 | primorsk
Processing Record 3 of Set 5 | kampot
Processing Record 4 of Set 5 | loandjili
Processing Record 5 of Set 5 | bur gabo
City not found. Skipping...
Processing Record 6 of Set 5 | flin flon
Processing Record 7 of Set 5 | airai
Processing Record 8 of Set 5 | murgab
Processing Record 9 of Set 5 | umba
Processing Record 10 of Set 5 | stromness
Processing Record 11 of Set 5 | sao filipe
Processing Record 12 of Set 5 | vila velha
Processing Record 13 of Set 5 | saint-augustin
Processing Record 14 of Set 5 | clyde river
Processing Record 15 of Set 5 | tsaratanana
Processing Record 16 of Set 5 | erzin
Processing Record 17 of Set 5 | vila franca do campo
Processing Record 18 of Set 5 | dikson
Processing Record 19 of Set 5 | roros
Processing Record 20 of Set 5 | kindu
Processing Record 21 of Set 5 | kikwit
Processing Record 22 of Set 5 | asau
Processing Record 23 of Set 5 | emba
Processing Record 24 of Set 5 | klaksvik
Processing Record 25 of Set 5 | ilulissat
Processing Record 26 of Set 5 | broken hill
Processing Record 27 of Set 5 | hammerfest
Processing Record 28 of Set 5 | amderma
City not found. Skipping...
Processing Record 29 of Set 5 | meshchovsk
Processing Record 30 of Set 5 | tateyama
Processing Record 31 of Set 5 | xixiang
Processing Record 32 of Set 5 | broome
Processing Record 33 of Set 5 | gotsu
Processing Record 34 of Set 5 | chateaubelair
Processing Record 35 of Set 5 | dunedin
Processing Record 36 of Set 5 | oussouye
Processing Record 37 of Set 5 | kurilsk
Processing Record 38 of Set 5 | havelock
Processing Record 39 of Set 5 | mar del plata
Processing Record 40 of Set 5 | avera
Processing Record 41 of Set 5 | chokurdakh
Processing Record 42 of Set 5 | bougouni
Processing Record 43 of Set 5 | barentsburg
City not found. Skipping...
Processing Record 44 of Set 5 | awbari
Processing Record 45 of Set 5 | samoded
Processing Record 46 of Set 5 | kozhevnikovo
Processing Record 47 of Set 5 | tiksi
Processing Record 48 of Set 5 | pacific grove
Processing Record 49 of Set 5 | buraydah
Processing Record 50 of Set 5 | kulhudhuffushi
Processing Record 1 of Set 6 | kavieng
Processing Record 2 of Set 6 | atbasar
Processing Record 3 of Set 6 | loubomo
Processing Record 4 of Set 6 | fairbanks
Processing Record 5 of Set 6 | pisco
Processing Record 6 of Set 6 | tura
Processing Record 7 of Set 6 | turukhansk
Processing Record 8 of Set 6 | luis correia
Processing Record 9 of Set 6 | maarianhamina
Processing Record 10 of Set 6 | altamira
Processing Record 11 of Set 6 | platteville
Processing Record 12 of Set 6 | san andres
Processing Record 13 of Set 6 | gannan
Processing Record 14 of Set 6 | egvekinot
Processing Record 15 of Set 6 | beyneu
Processing Record 16 of Set 6 | katsuura
Processing Record 17 of Set 6 | sadon
Processing Record 18 of Set 6 | marathon
Processing Record 19 of Set 6 | sirur
Processing Record 20 of Set 6 | lompoc
Processing Record 21 of Set 6 | namibe
Processing Record 22 of Set 6 | decatur
Processing Record 23 of Set 6 | brae
Processing Record 24 of Set 6 | lasa
Processing Record 25 of Set 6 | kruisfontein
Processing Record 26 of Set 6 | kangaatsiaq
Processing Record 27 of Set 6 | kodiak
Processing Record 28 of Set 6 | marzuq
Processing Record 29 of Set 6 | ahipara
Processing Record 30 of Set 6 | nabire
Processing Record 31 of Set 6 | la rioja
Processing Record 32 of Set 6 | shar
Processing Record 33 of Set 6 | balezino
Processing Record 34 of Set 6 | evensk
Processing Record 35 of Set 6 | athens
Processing Record 36 of Set 6 | tiverton
Processing Record 37 of Set 6 | petropavlovsk-kamchatskiy
Processing Record 38 of Set 6 | lagoa
Processing Record 39 of Set 6 | fort saint james
Processing Record 40 of Set 6 | murray bridge
Processing Record 41 of Set 6 | andros town
Processing Record 42 of Set 6 | la palma
Processing Record 43 of Set 6 | minot
Processing Record 44 of Set 6 | zhuhai
Processing Record 45 of Set 6 | gorontalo
Processing Record 46 of Set 6 | provideniya
Processing Record 47 of Set 6 | amapa
Processing Record 48 of Set 6 | jinchang
Processing Record 49 of Set 6 | sur
Processing Record 50 of Set 6 | lufkin
Processing Record 1 of Set 7 | peniche
Processing Record 2 of Set 7 | ketchikan
Processing Record 3 of Set 7 | the valley
Processing Record 4 of Set 7 | miandrivazo
Processing Record 5 of Set 7 | stanger
Processing Record 6 of Set 7 | pasighat
Processing Record 7 of Set 7 | fandriana
Processing Record 8 of Set 7 | turayf
Processing Record 9 of Set 7 | bambous virieux
Processing Record 10 of Set 7 | touros
Processing Record 11 of Set 7 | constitucion
Processing Record 12 of Set 7 | meulaboh
Processing Record 13 of Set 7 | cayenne
Processing Record 14 of Set 7 | gulshat
City not found. Skipping...
Processing Record 15 of Set 7 | sahrak
City not found. Skipping...
Processing Record 16 of Set 7 | rayong
Processing Record 17 of Set 7 | makakilo city
Processing Record 18 of Set 7 | vysokogornyy
Processing Record 19 of Set 7 | den helder
Processing Record 20 of Set 7 | ancud
Processing Record 21 of Set 7 | udachnyy
Processing Record 22 of Set 7 | naranjal
Processing Record 23 of Set 7 | fortuna
Processing Record 24 of Set 7 | port elizabeth
Processing Record 25 of Set 7 | minsk
Processing Record 26 of Set 7 | kandrian
Processing Record 27 of Set 7 | aitape
Processing Record 28 of Set 7 | gizo
Processing Record 29 of Set 7 | janauba
Processing Record 30 of Set 7 | codrington
Processing Record 31 of Set 7 | port hardy
Processing Record 32 of Set 7 | aquiraz
Processing Record 33 of Set 7 | narsaq
Processing Record 34 of Set 7 | krasnousolskiy
City not found. Skipping...
Processing Record 35 of Set 7 | hami
Processing Record 36 of Set 7 | punta cardon
Processing Record 37 of Set 7 | sambava
Processing Record 38 of Set 7 | kualakapuas
Processing Record 39 of Set 7 | mukhen
Processing Record 40 of Set 7 | dicabisagan
Processing Record 41 of Set 7 | coquimbo
Processing Record 42 of Set 7 | ivrea
Processing Record 43 of Set 7 | santiago del estero
Processing Record 44 of Set 7 | tres arroyos
Processing Record 45 of Set 7 | antalaha
Processing Record 46 of Set 7 | sorong
Processing Record 47 of Set 7 | guiyang
Processing Record 48 of Set 7 | umm lajj
Processing Record 49 of Set 7 | ossora
Processing Record 50 of Set 7 | kieta
Processing Record 1 of Set 8 | paamiut
Processing Record 2 of Set 8 | trincomalee
Processing Record 3 of Set 8 | mandalgovi
Processing Record 4 of Set 8 | nome
Processing Record 5 of Set 8 | hamada
Processing Record 6 of Set 8 | collie
Processing Record 7 of Set 8 | jiayuguan
Processing Record 8 of Set 8 | cocachacra
Processing Record 9 of Set 8 | barreirinhas
Processing Record 10 of Set 8 | manggar
Processing Record 11 of Set 8 | kirakira
Processing Record 12 of Set 8 | dukat
Processing Record 13 of Set 8 | katobu
Processing Record 14 of Set 8 | te anau
Processing Record 15 of Set 8 | lanzhou
Processing Record 16 of Set 8 | cap-aux-meules
Processing Record 17 of Set 8 | port shepstone
Processing Record 18 of Set 8 | kerrabe
City not found. Skipping...
Processing Record 19 of Set 8 | cabra
Processing Record 20 of Set 8 | yar-sale
Processing Record 21 of Set 8 | imeni poliny osipenko
Processing Record 22 of Set 8 | walvis bay
Processing Record 23 of Set 8 | nouadhibou
Processing Record 24 of Set 8 | tollose
Processing Record 25 of Set 8 | seoul
Processing Record 26 of Set 8 | luangwa
Processing Record 27 of Set 8 | santa rosa
Processing Record 28 of Set 8 | maragogi
Processing Record 29 of Set 8 | adrar
Processing Record 30 of Set 8 | chernyanka
Processing Record 31 of Set 8 | port-cartier
Processing Record 32 of Set 8 | rafai
Processing Record 33 of Set 8 | mehamn
Processing Record 34 of Set 8 | mahibadhoo

Processing Record 35 of Set 8 | anakapalle
Processing Record 36 of Set 8 | gat
Processing Record 37 of Set 8 | komsomolskiy
Processing Record 38 of Set 8 | halalo
City not found. Skipping...
Processing Record 39 of Set 8 | prachin buri
Processing Record 40 of Set 8 | college
Processing Record 41 of Set 8 | university place
Processing Record 42 of Set 8 | bengkulu
Processing Record 43 of Set 8 | nizhneyansk
City not found. Skipping...
Processing Record 44 of Set 8 | olinda
Processing Record 45 of Set 8 | san cristobal
Processing Record 46 of Set 8 | quatre cocos
Processing Record 47 of Set 8 | oranjemund
Processing Record 48 of Set 8 | mugur-aksy
Processing Record 49 of Set 8 | bangassou
Processing Record 50 of Set 8 | shiyan
Processing Record 1 of Set 9 | vestmannaeyjar
Processing Record 2 of Set 9 | sao gabriel da cachoeira
Processing Record 3 of Set 9 | metro
Processing Record 4 of Set 9 | trofors
Processing Record 5 of Set 9 | tarabha
Processing Record 6 of Set 9 | jijiga
Processing Record 7 of Set 9 | vacaria
Processing Record 8 of Set 9 | kathu
Processing Record 9 of Set 9 | bajo baudo
City not found. Skipping...
Processing Record 10 of Set 9 | marystown
Processing Record 11 of Set 9 | naze
Processing Record 12 of Set 9 | sosnogorsk
Processing Record 13 of Set 9 | konya
Processing Record 14 of Set 9 | comodoro rivadavia
Processing Record 15 of Set 9 | aykhal
Processing Record 16 of Set 9 | cap malheureux
Processing Record 17 of Set 9 | kavaratti
Processing Record 18 of Set 9 | kununurra
Processing Record 19 of Set 9 | sungaipenuh
Processing Record 20 of Set 9 | narasannapeta
Processing Record 21 of Set 9 | baghdad
Processing Record 22 of Set 9 | choma
Processing Record 23 of Set 9 | la grande
Processing Record 24 of Set 9 | udupi
Processing Record 25 of Set 9 | abu kamal
Processing Record 26 of Set 9 | karakulino
Processing Record 27 of Set 9 | miranda
Processing Record 28 of Set 9 | bom jesus
Processing Record 29 of Set 9 | tyukhtet
Processing Record 30 of Set 9 | saint-joseph
Processing Record 31 of Set 9 | sawakin
Processing Record 32 of Set 9 | jian
Processing Record 33 of Set 9 | raymondville
Processing Record 34 of Set 9 | pitimbu
Processing Record 35 of Set 9 | hurricane
Processing Record 36 of Set 9 | atar
Processing Record 37 of Set 9 | san quintin
Processing Record 38 of Set 9 | omboue
Processing Record 39 of Set 9 | tromso
Processing Record 40 of Set 9 | qujing
Processing Record 41 of Set 9 | polis
Processing Record 42 of Set 9 | labuhan
Processing Record 43 of Set 9 | lakatoro
Processing Record 44 of Set 9 | caravelas
Processing Record 45 of Set 9 | kirya
Processing Record 46 of Set 9 | noumea
Processing Record 47 of Set 9 | shizunai
Processing Record 48 of Set 9 | havoysund
Processing Record 49 of Set 9 | bulaevo
Processing Record 50 of Set 9 | salinopolis
Processing Record 1 of Set 10 | slave lake
Processing Record 2 of Set 10 | samalaeulu
City not found. Skipping...
Processing Record 3 of Set 10 | bolitoc
Processing Record 4 of Set 10 | ukiah
Processing Record 5 of Set 10 | tsihombe
City not found. Skipping...
Processing Record 6 of Set 10 | shakiso
Processing Record 7 of Set 10 | lacey
Processing Record 8 of Set 10 | kambove
Processing Record 9 of Set 10 | mumford
Processing Record 10 of Set 10 | ust-kut
Processing Record 11 of Set 10 | mergui
City not found. Skipping...
Processing Record 12 of Set 10 | buqayq
City not found. Skipping...
Processing Record 13 of Set 10 | tabas
Processing Record 14 of Set 10 | zheleznodorozhnyy
Processing Record 15 of Set 10 | darhan
Processing Record 16 of Set 10 | dabola
Processing Record 17 of Set 10 | vestmanna
Processing Record 18 of Set 10 | hede
Processing Record 19 of Set 10 | sylacauga
Processing Record 20 of Set 10 | collierville
Processing Record 21 of Set 10 | weiser
Processing Record 22 of Set 10 | barcelos
Processing Record 23 of Set 10 | ambilobe
Processing Record 24 of Set 10 | svetlogorsk
Processing Record 25 of Set 10 | karratha
Processing Record 26 of Set 10 | sokoni
Processing Record 27 of Set 10 | shimoda
Processing Record 28 of Set 10 | karkaralinsk
City not found. Skipping...
Processing Record 29 of Set 10 | mahebourg
Processing Record 30 of Set 10 | quimper
Processing Record 31 of Set 10 | olafsvik
Processing Record 32 of Set 10 | hamilton
Processing Record 33 of Set 10 | samusu
City not found. Skipping...
Processing Record 34 of Set 10 | aksarka
Processing Record 35 of Set 10 | de aar
Processing Record 36 of Set 10 | coronado
Processing Record 37 of Set 10 | ekibastuz
Processing Record 38 of Set 10 | nyurba
Processing Record 39 of Set 10 | zhadovka
Processing Record 40 of Set 10 | halifax
Processing Record 41 of Set 10 | tuatapere
Processing Record 42 of Set 10 | umzimvubu
City not found. Skipping...
Processing Record 43 of Set 10 | marawi
Processing Record 44 of Set 10 | bandiagara
Processing Record 45 of Set 10 | isangel
Processing Record 46 of Set 10 | nanortalik
Processing Record 47 of Set 10 | feldkirchen an der donau
Processing Record 48 of Set 10 | grand-lahou
Processing Record 49 of Set 10 | svetlaya
Processing Record 50 of Set 10 | klyuchi
Processing Record 1 of Set 11 | kupino
Processing Record 2 of Set 11 | flinders
Processing Record 3 of Set 11 | yarmouth
Processing Record 4 of Set 11 | maldonado
Processing Record 5 of Set 11 | sola
Processing Record 6 of Set 11 | troitsko-pechorsk
Processing Record 7 of Set 11 | leningradskiy
Processing Record 8 of Set 11 | akdepe
Processing Record 9 of Set 11 | tadine
Processing Record 10 of Set 11 | tawnat
City not found. Skipping...
Processing Record 11 of Set 11 | hovd
Processing Record 12 of Set 11 | koumac
Processing Record 13 of Set 11 | henties bay
Processing Record 14 of Set 11 | pedernales
Processing Record 15 of Set 11 | haines junction
Processing Record 16 of Set 11 | galesong
Processing Record 17 of Set 11 | nam som
Processing Record 18 of Set 11 | biak
Processing Record 19 of Set 11 | kuruman
Processing Record 20 of Set 11 | sioux lookout
Processing Record 21 of Set 11 | jiwani
Processing Record 22 of Set 11 | baloda bazar
Processing Record 23 of Set 11 | grande prairie
Processing Record 24 of Set 11 | sherlovaya gora
Processing Record 25 of Set 11 | port-gentil
Processing Record 26 of Set 11 | nosy varika
Processing Record 27 of Set 11 | chapais
Processing Record 28 of Set 11 | sebeta
Processing Record 29 of Set 11 | srednekolymsk
Processing Record 30 of Set 11 | aksu
Processing Record 31 of Set 11 | mount gambier
Processing Record 32 of Set 11 | wencheng
Processing Record 33 of Set 11 | krutinka
Processing Record 34 of Set 11 | alice town
Processing Record 35 of Set 11 | meyungs
City not found. Skipping...
Processing Record 36 of Set 11 | falealupo
City not found. Skipping...
Processing Record 37 of Set 11 | beloha
Processing Record 38 of Set 11 | alaverdi
Processing Record 39 of Set 11 | grindavik
Processing Record 40 of Set 11 | kendari
Processing Record 41 of Set 11 | pringsewu
Processing Record 42 of Set 11 | tottori
Processing Record 43 of Set 11 | sao jose da coroa grande
Processing Record 44 of Set 11 | shingu
Processing Record 45 of Set 11 | diamantino
Processing Record 46 of Set 11 | valleyview
Processing Record 47 of Set 11 | phun phin
City not found. Skipping...
Processing Record 48 of Set 11 | nuuk
Processing Record 49 of Set 11 | ban dung
Processing Record 50 of Set 11 | anadyr
Processing Record 1 of Set 12 | lodja
Processing Record 2 of Set 12 | san policarpo
Processing Record 3 of Set 12 | darnah
Processing Record 4 of Set 12 | tabiauea
City not found. Skipping...
Processing Record 5 of Set 12 | tambun
Processing Record 6 of Set 12 | bahar
Processing Record 7 of Set 12 | ballina
Processing Record 8 of Set 12 | lodwar
Processing Record 9 of Set 12 | kemijarvi
Processing Record 10 of Set 12 | port lincoln
Processing Record 11 of Set 12 | dwarka
Processing Record 12 of Set 12 | pemex
Processing Record 13 of Set 12 | abbeville
Processing Record 14 of Set 12 | alofi
Processing Record 15 of Set 12 | kautokeino
Processing Record 16 of Set 12 | korla
Processing Record 17 of Set 12 | sorland
Processing Record 18 of Set 12 | nguiu
City not found. Skipping...
Processing Record 19 of Set 12 | mezen

Processing Record 20 of Set 12 | dalbandin
Processing Record 21 of Set 12 | russell
Processing Record 22 of Set 12 | urazovo
Processing Record 23 of Set 12 | chabahar
Processing Record 24 of Set 12 | suoyarvi
Processing Record 25 of Set 12 | vilhena
Processing Record 26 of Set 12 | ternate
Processing Record 27 of Set 12 | chibombo
Processing Record 28 of Set 12 | salinas
Processing Record 29 of Set 12 | zonalnoye
City not found. Skipping...
Processing Record 30 of Set 12 | corinto
Processing Record 31 of Set 12 | oranjestad
Processing Record 32 of Set 12 | muros
Processing Record 33 of Set 12 | limbang
Processing Record 34 of Set 12 | sudova vyshnya
Processing Record 35 of Set 12 | lianzhou
Processing Record 36 of Set 12 | reinosa
Processing Record 37 of Set 12 | zhigansk
Processing Record 38 of Set 12 | along
Processing Record 39 of Set 12 | lolua
City not found. Skipping...
Processing Record 40 of Set 12 | cabedelo
Processing Record 41 of Set 12 | tsogni
Processing Record 42 of Set 12 | lufilufi
Processing Record 43 of Set 12 | cajati
--------------------
Data Retrieval Complete
--------------------

In [13]:
len(city_data)

553

In [14]:
# List of dictionaries to a pandas DataFrame

city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,souillac,-20.5167,57.5167,70.18,scattered clouds,0.00,0,73,40,12.66,MU
1,albany,42.6001,-73.9662,77.18,clear sky,0.00,0,61,1,6.31,US
2,high rock,26.6208,-78.2833,84.22,clear sky,0.00,0,73,0,12.71,BS
3,avarua,-21.2078,-159.7750,77.05,broken clouds,0.00,0,65,75,5.75,CK
4,tha chang,9.2642,99.1922,80.24,moderate rain,1.33,0,94,75,2.30,TH
5,jamestown,42.0970,-79.2353,76.64,clear sky,0.00,0,65,0,9.22,US
6,morden,49.1919,-98.1014,75.06,clear sky,0.00,0,57,7,11.50,CA
7,bethel,41.3712,-73.4140,72.64,clear sky,0.00,0,70,0,1.01,US
8,talnakh,69.4865,88.3972,49.21,broken clouds,0.00,0,53,63,20.27,RU
9,severo-kurilsk,50.6789,156.1250,60.13,few clouds,0.00,0,84,22,7.67,RU

In [15]:
# Organizing columns in the order we want them to appear

new_column_order = ['City', 'Country', 'Lat', 'Lng', 'Max Temp', 'Humidity', 
                    'Cloudiness', 'Wind Speed', 'Current Description', 
                    'Rain (inches)', 'Snow (inches)']

# Assign a new or the same DataFrame the new column order

city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain (inches),Snow (inches)
0,souillac,MU,-20.5167,57.5167,70.18,73,40,12.66,scattered clouds,0.00,0
1,albany,US,42.6001,-73.9662,77.18,61,1,6.31,clear sky,0.00,0
2,high rock,BS,26.6208,-78.2833,84.22,73,0,12.71,clear sky,0.00,0
3,avarua,CK,-21.2078,-159.7750,77.05,65,75,5.75,broken clouds,0.00,0
4,tha chang,TH,9.2642,99.1922,80.24,94,75,2.30,moderate rain,1.33,0
5,jamestown,US,42.0970,-79.2353,76.64,65,0,9.22,clear sky,0.00,0
6,morden,CA,49.1919,-98.1014,75.06,57,7,11.50,clear sky,0.00,0
7,bethel,US,41.3712,-73.4140,72.64,70,0,1.01,clear sky,0.00,0
8,talnakh,RU,69.4865,88.3972,49.21,53,63,20.27,broken clouds,0.00,0
9,severo-kurilsk,RU,50.6789,156.1250,60.13,84,22,7.67,few clouds,0.00,0

In [16]:
raining_cities = city_data_df.loc[city_data_df['Rain (inches)'] > 0]
raining_cities.head()

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain (inches),Snow (inches)
4,tha chang,TH,9.2642,99.1922,80.24,94,75,2.30,moderate rain,1.33,0
24,butaritari,KI,3.0707,172.7902,81.93,80,79,16.71,light rain,0.26,0
32,lebu,CL,-37.6167,-73.6500,48.36,80,100,16.44,light rain,0.27,0
35,bubaque,GW,11.2833,-15.8333,79.61,84,46,12.77,light rain,0.38,0
39,faanui,PF,-16.4833,-151.7500,78.17,74,1,8.05,light rain,0.59,0

In [17]:
snowing_cities = city_data_df.loc[city_data_df['Snow (inches)'] > 0]
snowing_cities

Empty DataFrame
Columns: [City, Country, Lat, Lng, Max Temp, Humidity, Cloudiness, Wind Speed, Current Description, Rain (inches), Snow (inches)]
Index: []

In [22]:
# Create the output file (CSV)

output_data_file = 'Weather_Database.csv'

# Export the City_Data into a CSV

city_data_df.to_csv(output_data_file, index_label='City_ID')